#!/bin/sh
set -e
# Install a document icon separately from the application icon. MIME metadata
# and the application desktop entry are generated by electron-builder.
install -D -m 644 /opt/MOSE/resources/assets/mosp.png /usr/share/icons/hicolor/256x256/mimetypes/application-x-mose-project.png
if command -v update-mime-database >/dev/null 2>&1; then update-mime-database /usr/share/mime; fi
if command -v gtk-update-icon-cache >/dev/null 2>&1; then gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor; fi
if command -v update-desktop-database >/dev/null 2>&1; then update-desktop-database /usr/share/applications; fi
