[project]
name = "moys-asr-workflow"
version = "1.4.0"
description = "A small cloud ASR API to local subtitle-editor workflow."
readme = "README.md"
requires-python = ">=3.11"
license = { text = "AGPL-3.0-only" }
dependencies = [
    "jieba>=0.42",
    "opencc-python-reimplemented>=0.1.7",
    "pywebview>=6.2.1; sys_platform != 'linux'",
    "pywebview[qt]>=6.2.1; sys_platform == 'linux'",
    "requests>=2.28",
    "numpy>=2.2,<2.5",
]

[project.optional-dependencies]
local-cu130 = [
    "accelerate>=1.12",
    "funasr>=1.2.6",
    "hf-xet>=1.5",
    "qwen-asr>=0.0.6",
    "torch>=2.13",
    "torchaudio",
]

local-xpu = [
    "accelerate>=1.12",
    "funasr>=1.2.6",
    "hf-xet>=1.5",
    "qwen-asr>=0.0.6",
    "torch",
    "torchaudio",
    "pytorch-triton-xpu",
]
ocr = [
    "onnxruntime>=1.18",
    "pillow>=10.0.0",
    "rapidocr>=3.9.0",
]

[tool.uv]
conflicts = [
  [
    { extra = "local-xpu" },
    { extra = "local-cu130" },
  ],
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[[tool.uv.index]]
name = "pytorch-xpu"
url = "https://download.pytorch.org/whl/xpu"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu130", marker = "sys_platform == 'win32'", extra = "local-cu130" },
  { index = "pytorch-xpu", marker = "sys_platform == 'win32'", extra = "local-xpu" },
]
torchaudio = [
  { index = "pytorch-cu130", marker = "sys_platform == 'win32'", extra = "local-cu130" },
  { index = "pytorch-xpu", marker = "sys_platform == 'win32'", extra = "local-xpu" },
]
pytorch-triton-xpu = [
  { index = "pytorch-xpu", extra = "local-xpu" },
]

[dependency-groups]
build = [
    "pyinstaller==6.16.0",
]
