from __future__ import annotations

import unittest

from scripts.freeze_cpu_requirements import freeze_cpu_requirements_text


class FreezeCpuRequirementsTests(unittest.TestCase):
    def test_strips_cuda_local_version_and_hash_lines(self) -> None:
        """Given a uv export body, When freezing, Then versions stay pinned but hashes go."""
        source = "\n".join(
            [
                "torch==2.13.0+cu130 ; sys_platform != 'darwin' \\",
                "    --hash=sha256:2efab1e83604ca628c6d85b9e188c153690980498d1297081a9dad704919303c \\",
                "    --hash=sha256:45e97bd9bc0416f4f4190b5098c55119a389fa5a7c8bbf2639f08f1d04e0a0dc",
                "    # via moys-asr-workflow",
                "",
                "# header comment",
            ]
        )

        frozen = freeze_cpu_requirements_text(source)

        self.assertIn("torch==2.13.0 ; sys_platform != 'darwin'\n", frozen)
        self.assertNotIn("+cu130", frozen)
        self.assertNotIn("--hash=", frozen)
        self.assertIn("    # via moys-asr-workflow", frozen)
        self.assertIn("# header comment", frozen)
        # torch 主清单含多个环境分支时，darwin 分支同样只保留纯 pin。
        self.assertTrue(frozen.endswith("\n"))

    def test_drops_nvidia_blocks_wholesale(self) -> None:
        """Given cu-build-only nvidia deps, When freezing, Then whole blocks vanish."""
        source = "\n".join(
            [
                "funasr==1.3.29 \\",
                "    --hash=sha256:aa \\",
                "    # via qwen-asr",
                "",
                "nvidia-cublas==13.1.1.3 ; sys_platform == 'linux' \\",
                "    --hash=sha256:cc \\",
                "    # via torch",
                "nvidia-cudnn-cu13==9.20.0.48 ; sys_platform == 'linux'",
                "torchaudio==2.11.0+cu130 ; sys_platform != 'darwin' \\",
                "    --hash=sha256:dd \\",
                "    # via moys-asr-workflow",
            ]
        )

        frozen = freeze_cpu_requirements_text(source)

        self.assertNotIn("nvidia-", frozen)
        self.assertIn("funasr==1.3.29\n", frozen)
        self.assertIn("torchaudio==2.11.0 ; sys_platform != 'darwin'", frozen)

    def test_non_nvidia_blocks_keep_their_comments(self) -> None:
        """Given normal blocks, When freezing, Then statement loses backslash and comments survive."""
        source = "\n".join(
            [
                "# This file was autogenerated by uv via:",
                "#    uv export --frozen --extra local --no-dev --format requirements-txt",
                "accelerate==1.12.0 \\",
                "    --hash=sha256:a1 \\",
                "    --hash=sha256:a2",
                "    # via",
                "    #   moys-asr-workflow",
                "    #   qwen-asr",
                "",
                "flask==3.1.2",
                "    # via requests",
            ]
        )

        frozen = freeze_cpu_requirements_text(source)

        self.assertIn("accelerate==1.12.0\n", frozen)
        self.assertNotIn("\\", frozen)
        self.assertIn("    #   qwen-asr", frozen)
        self.assertIn("flask==3.1.2", frozen)
        self.assertIn("    # via requests", frozen)

    def test_rejects_unexpected_structures_instead_of_corrupting(self) -> None:
        """Given a continuation that is neither hash nor comment, Then fail loudly."""
        with self.assertRaises(ValueError):
            freeze_cpu_requirements_text("torch==2.13.0+cu130 \\\n    -r extra.txt")
        with self.assertRaises(ValueError):
            freeze_cpu_requirements_text("    --hash=sha256:orphan \\")

    def test_moss_style_input_without_hashes_is_unchanged(self) -> None:
        """Given hash-free uv pip compile output, When freezing, Then only +cuXXX matters."""
        source = "\n".join(
            [
                "torch==2.13.0+cu130 \\",
                "    # via -r moss-requirements.in",
                "transformers==5.2.1",
            ]
        )

        frozen = freeze_cpu_requirements_text(source)

        self.assertEqual(frozen, "torch==2.13.0\n    # via -r moss-requirements.in\ntransformers==5.2.1\n")


if __name__ == "__main__":
    unittest.main()
